/*
Each new term in the Fibonacci sequence is
generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms
will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci
sequence whose values do not exceed four
million, find the sum of the even-valued terms.
*/

package sdegutishomework

func fibonacci(i int) int {
  first := 1
  second := 2
  if i == 0 {
    return first
  }
  if i == 1 {
    return second
  }
  current := 0
  for n := 2; n <= i; n++ {
    current = first + second
    first = second
    second = current
  }
  return current
}
